apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-dev
    app.kubernetes.io/platform: prod.colbert.def
    version: $IMG_TAG
  name: frontend-dev
  namespace: planification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-dev
      app.kubernetes.io/platform: prod.colbert.def
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend-dev
        app.kubernetes.io/platform: prod.colbert.def
    spec:
      containers:
        - image: $IMG_NAME:$IMG_TAG@$IMG_DIGEST
          imagePullPolicy: IfNotPresent
          name: frontend-container
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: '200m'
              memory: 100Mi
            requests:
              cpu: '200m'
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: NODE_ENV
              value: production
            - name: PUBLIC_TILE_STYLE
              value: >-
                https://openstreetmap-tileserver.apps.colbert.marine.defensecdd.gouv.fr/styles/basic-preview/style.json
            - name: PUBLIC_BACKEND_URL
              value: 'https://scheduler-backend.apps.prod.colbert.def/scheduler'
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: '5432'
            - name: DATABASE_USER
              value: admin
            - name: DATABASE_PASSWORD
              value: secretpassword
            - name: DATABASE_DB
              value: scheduling-app
            - name: APP_URL
              value: 'https://scheduler.apps.colbert.marine.defensecdd.gouv.fr'
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
---
kind: Service
apiVersion: v1
metadata:
  name: frontend-dev-svc
  namespace: planification
  labels:
    app.kubernetes.io/platform: prod.colbert.def
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 3000-tcp
      protocol: TCP
      port: 80
      targetPort: 3000
  internalTrafficPolicy: Cluster
  selector:
    app: frontend-dev
    app.kubernetes.io/platform: prod.colbert.def
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: frontend-dev
  namespace: planification
  labels:
    app.kubernetes.io/platform: prod.colbert.def
spec:
  host: scheduler-dev.apps.prod.colbert.def
  to:
    kind: Service
    name: frontend-svc
    weight: 100
  port:
    targetPort: 3000-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
