services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: local
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.fr
      PGADMIN_DEFAULT_PASSWORD: admin

  app:
    build: .
    restart: always
    ports:
      - 4173:4173
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:secretpassword@db:5432/local
      SECURED: UNSECURED
      APP_URL: http://localhost:8000
      PUBLIC_TILE_STYLE: https://basemaps.cartocdn.com/gl/positron-gl-style/style.json
      NODE_TLS_REJECT_UNAUTHORIZED: 0